---

- name: Override vars for PPAs.
  include_vars: ppa.yml
  when: apt_source_config.0.source_string is defined
    and not apt_source_config.0.source_string.startswith("ppa:")


- name: Remove old pin files that do not have a .pref suffix.
  file:
    path: "{{ item.filepath|default(__apt_source_preferences_filepath) }}{{ item.pattern|regex_replace('[^A-Za-z0-9]', '')}}"
    state: absent
  with_items:
    - "{{ __apt_source_default_pin }}"
    - "{{ apt_source_config.0.packages }}"
  when:
    item.pattern is defined



# See apt_preferences manpage. 200 is a good choice because it means lower
# than the default repo priority (500) but higher than installed (100) so
# when a package from the source is installed, it will still get upgraded.
- name: Set repo packages to low priority.
  template:
    src: preferences.j2
    dest: "{{ item.filepath|default(__apt_source_preferences_filepath) }}{{ item.pattern|regex_replace('[^A-Za-z0-9]', '')}}.pref"
    owner: root
    group: root
    mode: 0644
  # debug: var=item
  with_items:
    - "{{ __apt_source_default_pin }}"
    - "{{ apt_source_config.0.packages }}"
  when:
        apt_source_state != "absent" and
        item.pattern is defined and
        item.absent is not defined

- name: Remove package pins.
  file:
    path: "{{ item.filepath|default(__apt_source_preferences_filepath) }}{{ item.pattern|regex_replace('[^A-Za-z0-9]', '')}}"
    state: absent
  with_items:
    - "{{ __apt_source_default_pin }}"
    - "{{ apt_source_config.0.packages }}"
  when: apt_source_config.0.state is defined and
        apt_source_config.0.state == 'absent' and
        item.pattern is defined

- name: Remove package pins (source kept).
  file:
    path: "{{ item.filepath|default(__apt_source_preferences_filepath) }}{{ item.pattern|regex_replace('[^A-Za-z0-9]', '')}}"
    state: absent
  when: (apt_source_config.0.state is not defined or
        apt_source_config.0.state != "absent") and item.absent is defined and
        item.pattern is defined
  with_items:
    - "{{ __apt_source_default_pin }}"
    - "{{ apt_source_config.0.packages }}"
